FROM openjdk:8-jre-alpine
RUN apk update && apk upgrade && apk add --no-cache bash

VOLUME ["/conf"]
WORKDIR /app
COPY burst.jar /app
COPY html /app/html
COPY conf/brs.properties.mariadb /conf/brs.properties
COPY conf/brs-default.properties /conf/brs-default.properties
COPY conf/logging-default.properties /conf/logging-default.properties
EXPOSE 8125 8123 8121
ENTRYPOINT ["java", "-classpath", "/app/burst.jar:/conf", "brs.Burst"]
